# Global configuration of pipeline
global:
  save_path: ./output

# Simplified Configuration for LLM compression
model:
  name: DeepSeek
  model_path: deepseek-ai/DeepSeek-R1
  trust_remote_code: true
  low_cpu_mem_usage: true
  use_cache: false
  torch_dtype: fp8
  device_map: auto

# Compression configuration
compression:
  name: PTQ
  quantization:
    name: fp8_static     # Supported: fp8_static, w4a8_fp8
    bits: 8                # Quantization bits (8)
    low_memory: false  # Use less gpu/cpu memory
    quant_method:
      weight: "per-tensor"
      activation: "per-tensor"
    ignore_layers:         # Skip quantization for these layers
      - "lm_head"
      - "model.embed_tokens"

# Dataset for calibration
dataset:
  name: TextDataset
  data_path: your/data/path
  max_seq_length: 4096
  num_samples: 512
  batch_size: 1
