# Copyright 2025 Tencent Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch

__all__ = ["Catcher"]


class Catcher(torch.nn.Module):
    """Intercepts the first transformer layer to capture inputs and kwargs.

    Uses dynamic list storage: each sample's hidden_states and kwargs are
    stored independently, preserving their original seq_len. This eliminates
    the need for seq_len trimming between inps and layer_kwargs.

    When ``max_seq_length`` is set, samples whose seq_len exceeds the limit
    are truncated (along with seq_len-dependent kwargs) to act as a VRAM
    guard without affecting shorter samples.
    """

    # Keys to discard when capturing layer kwargs.
    # past_key_values (DynamicCache) is generated by HF generate() but is
    # incompatible with GPTQ's layer-by-layer forward (causes kv_len mismatch).
    _FILTER_KWARGS = {"past_key_values", "past_key_value"}

    # Kwargs whose dim-2 (seq_len dimension) should be truncated together
    # with hidden_states when max_seq_length is enforced.
    _SEQ_DIM_KWARGS = {"position_ids"}

    def __init__(self, module, max_seq_length=None):
        super().__init__()
        self.module = module
        self.max_seq_length = max_seq_length
        # Dynamic list storage: each element is a tensor [1, seq_len_i, hidden]
        self.captured_inputs = []
        # Per-sample kwargs list (each element is a filtered kwargs dict)
        self.captured_kwargs = []

    @staticmethod
    def _truncate_seq(tensor, max_len, dim=1):
        """Truncate a tensor along the given dimension to max_len."""
        if tensor is None or tensor.shape[dim] <= max_len:
            return tensor
        return tensor.narrow(dim, 0, max_len)

    @classmethod
    def _truncate_kwargs(cls, kwargs, max_len):
        """Truncate seq_len-dependent values inside kwargs dict."""
        out = {}
        for k, v in kwargs.items():
            if k in cls._SEQ_DIM_KWARGS and isinstance(v, torch.Tensor):
                # position_ids shape: [batch, seq_len]
                out[k] = cls._truncate_seq(v, max_len, dim=-1)
            elif k == "attention_mask" and isinstance(v, torch.Tensor):
                truncated = cls._truncate_seq(v, max_len, dim=-1)
                if truncated.dim() >= 3:
                    truncated = cls._truncate_seq(truncated, max_len, dim=-2)
                out[k] = truncated
            elif k == "position_embeddings" and isinstance(v, tuple):
                # position_embeddings is (cos, sin), each [batch, seq_len, dim]
                out[k] = tuple(cls._truncate_seq(t, max_len, dim=1) for t in v)
            else:
                out[k] = v
        return out

    @classmethod
    def _capture_samples(cls, inp, kwargs, max_seq_length, captured_inputs, captured_kwargs):
        """Core capture logic shared by both replace mode and hook mode.

        Splits a batched input into per-sample tensors, filters kwargs,
        applies seq_len truncation, and appends to the provided lists.
        """
        # Filter out keys that are incompatible with layer-by-layer forward
        filtered = {
            k: v for k, v in kwargs.items() if k not in cls._FILTER_KWARGS and k != "hidden_states"
        }

        for i in range(inp.shape[0]):
            sample = inp[i : i + 1].detach()

            if max_seq_length is not None and sample.shape[1] > max_seq_length:
                sample = sample[:, :max_seq_length, :]
                sample_kwargs = cls._truncate_kwargs(filtered, max_seq_length)
            else:
                sample_kwargs = filtered

            captured_inputs.append(sample)
            captured_kwargs.append(sample_kwargs)

    def forward(self, inp, **kwargs):
        self._capture_samples(
            inp,
            kwargs,
            self.max_seq_length,
            self.captured_inputs,
            self.captured_kwargs,
        )
        raise ValueError

    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            return getattr(self.module, name)
